### ISSUE TITLE
gamestate stuck in WaitingForPlayers

### ISSUE THREAD

**Issue by mick-warehime** [danbarragan/drawydraw#14]
repro steps
1) start servers
2) go to  localhost:xxx
3) click the debug 'WaitingForPlayers' button
4) click the debug 'InitialPromptCreation' button
5) wait 3 seconds until the state starts jumping back and forth between states.

this is artificial because we have the custom jump-to-buttons so i'm not sure if this is a real bug but something about the way we poll the game state every 3 second. on screen exit we need to stop polling game state for a given screen.

**Comment by mick-warehime** [comment]
dan - i haven't looked into this at all. do you have an idea how we can stop polling when we leave a given state?

**Comment by danbarragan** [comment]
Yah we shouldn't blindly call setInterval, we need to deregister that thing when the component dismounts. I'll fix it tomorrow
