### ISSUE TITLE
Refactor test setup code in main_test.go

### ISSUE THREAD

**Issue by danbarragan** [danbarragan/drawydraw#22]
Problems:
- Tons of code duplication
- Tests for a state depend on all previous states working
- Tests do not clean up after themselves

**Comment by mick-warehime** [comment]
did you start working on this already? i didnt see it was assigned (i'm a github colab newb :/ ) and made a few commits to clean up the code duplication part - i haven't made any progress on testing the returned game state / cleaning up after tests. nbd if you already started

**Comment by danbarragan** [comment]
Noooo go for it! Thank you so much! I will look at PR later tonight!

**Comment by mick-warehime** [comment]
fixed in #23
